namespace sdslib.Enums
{
    public enum EResourceType
    {
        Actors,
        AnimalTrafficPaths,
        AnimatedTexture,
        Animation2,
        AudioSectors,
        Collisions,
        Cutscene,
        Effects,
        EntityDataStorage,
        FrameNameTable,
        FrameResource,
        FxActor,
        FxAnimSet,
        IndexBufferPool,
        ItemDesc,
        MemFile,
        Mipmap,
        NAV_AIWORLD_DATA,
        NAV_OBJ_DATA,
        PREFAB,
        Script,
        Sound,
        SoundTable,
        Speech,
        Table,
        Texture,
        Translokator,
        VertexBufferPool,
        XML,
        Flash,
        SystemObjectDatabase
    }
}
